# Generated by Django 6.0.5 on 2026-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("autor", models.CharField(max_length=150, verbose_name="Autor")),
                (
                    "anio_publicacion",
                    models.IntegerField(verbose_name="Año de publicación"),
                ),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="¿Está disponible?"),
                ),
            ],
        ),
    ]
